from main_code.model.fm import FM
from main_code.model.lr import LR
from main_code.model.deepfm import DeepFM
from main_code.model.dcn import DCN
from main_code.model.dcnv2 import DCNv2
from main_code.model.fibinet import Fibinet
from main_code.model.wdl import WDL
from main_code.model.ccpm import CCPM
from main_code.model.pnn import PNN
from main_code.model.mlr import MLR
from main_code.model.afm import AFM
from main_code.model.nfm import NFM
from main_code.model.xdeepfm import xDeepFM
from main_code.model.ffm import FFM
from main_code.model.fwfm import FwFM
from main_code.model.autoint import AutoInt
from main_code.model.onn import ONN
from main_code.model.fgcnn import FGCNN
from main_code.model.flen import FLEN
from main_code.model.ifm import IFM
from main_code.model.fmfm import FmFM
from main_code.model.difm import DIFM
from main_code.model.edcn import EDCN